// Model replacement pipeline (18D follow-up): turn a Higgsfield
// multi_image_to_3d result (textured+PBR mesh, Meshy humanoid rig, idle
// animation) into a full game character folder:
//   1) the source GLB becomes <char>/idle.glb (animation renamed 'idle');
//   2) every OTHER clip of the character is regenerated by retargeting the
//      existing library clips (old Mixamo rig) onto the NEW skeleton with the
//      world-space engine from retargetMeshyClip.mjs - the engine is
//      direction-agnostic (canonical bone names on both sides).
// The old clips are read from a backup folder so the tool is idempotent.
//
// Usage: node tools/art/importHiggsfieldModel.mjs <downloaded.glb> <charFolder>
//   e.g. node tools/art/importHiggsfieldModel.mjs scratch/sonya_v2.glb female_pm
import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { retargetMeshyClip } from './retargetMeshyClip.mjs'

const ROOT = process.cwd()
const CHAR_DIR = join(ROOT, 'public', 'character')

function readGlb(file) {
  const buf = readFileSync(file)
  if (buf.readUInt32LE(0) !== 0x46546c67) throw new Error(`${file}: not a GLB`)
  const jsonLength = buf.readUInt32LE(12)
  const json = JSON.parse(buf.subarray(20, 20 + jsonLength).toString('utf8'))
  const binHeader = 20 + jsonLength
  let bin = Buffer.alloc(0)
  if (binHeader < buf.length) {
    const binLength = buf.readUInt32LE(binHeader)
    bin = buf.subarray(binHeader + 8, binHeader + 8 + binLength)
  }
  return { json, bin }
}

function writeGlb(file, json, bin) {
  let jsonBuf = Buffer.from(JSON.stringify(json), 'utf8')
  while (jsonBuf.length % 4 !== 0) jsonBuf = Buffer.concat([jsonBuf, Buffer.from(' ')])
  let binBuf = bin
  while (binBuf.length % 4 !== 0) binBuf = Buffer.concat([binBuf, Buffer.alloc(1)])
  const total = 12 + 8 + jsonBuf.length + 8 + binBuf.length
  const out = Buffer.alloc(total)
  out.writeUInt32LE(0x46546c67, 0)
  out.writeUInt32LE(2, 4)
  out.writeUInt32LE(total, 8)
  out.writeUInt32LE(jsonBuf.length, 12)
  out.writeUInt32LE(0x4e4f534a, 16)
  jsonBuf.copy(out, 20)
  const at = 20 + jsonBuf.length
  out.writeUInt32LE(binBuf.length, at)
  out.writeUInt32LE(0x004e4942, at + 4)
  binBuf.copy(out, at + 8)
  writeFileSync(file, out)
  return total
}

const [sourceGlb, charFolder] = process.argv.slice(2)
if (!sourceGlb || !charFolder) {
  console.error('usage: node tools/art/importHiggsfieldModel.mjs <downloaded.glb> <charFolder>')
  process.exit(1)
}

const targetDir = join(CHAR_DIR, charFolder)
// backups live OUTSIDE public/ so they never ship in the production build
const backupDir = join(ROOT, 'assets', 'source', 'models-mixamo-backup', charFolder)

// 1) one-time backup of the old Mixamo clip set (retarget SOURCE of truth)
if (!existsSync(backupDir)) {
  mkdirSync(backupDir, { recursive: true })
  for (const f of readdirSync(targetDir).filter((f) => f.endsWith('.glb'))) {
    copyFileSync(join(targetDir, f), join(backupDir, f))
  }
  console.log(`backup: ${backupDir}`)
}

// 2) new base idle.glb: rename the baked animation to 'idle'
const base = readGlb(sourceGlb)
if (!base.json.animations?.length) throw new Error('source GLB carries no animation - regenerate with enable_animation')
base.json.animations = [base.json.animations[0]]
base.json.animations[0].name = 'idle'
const idleOut = join(targetDir, 'idle.glb')
const bytes = writeGlb(idleOut, base.json, base.bin)
console.log(`idle.glb: ${Math.round(bytes / 1024)} KB, tris≈${(base.json.meshes ?? []).length} meshes, skins ${(base.json.skins ?? []).length}`)

// 3) retarget every other clip from the Mixamo backup onto the new skeleton
const CLIPS = ['walk', 'sit', 'type', 'drink', 'sitIdle', 'sofaSit', 'talk', 'look', 'agree', 'celebrate', 'explain', 'facepalm']
for (const clip of CLIPS) {
  const src = join(backupDir, `${clip}.glb`)
  if (!existsSync(src)) {
    console.log(`  ${clip}: (absent in old set, skipped)`)
    continue
  }
  const r = retargetMeshyClip(src, idleOut, join(targetDir, `${clip}.glb`), clip)
  console.log(`  ${clip}: ${r.frames}f ${r.durationSec}s ${r.bones} bones x${r.heightRatio} ${r.kb} KB`)
}
console.log('IMPORT_DONE')
